version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: gestion_connect_postgres
    environment:
      POSTGRES_DB: gestion_connect
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: gestion_connect_redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  freeradius:
    image: freeradius/freeradius-server:latest
    container_name: gestion_connect_radius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./radius-config:/etc/freeradius
    restart: unless-stopped

volumes:
  pgdata:
